/* ─────────────────────────────────────────
   AKVA STUDIO — main.js
   ───────────────────────────────────────── */

// ── TRANSLATIONS ──────────────────────────
const translations = {
  lt: {
    nav_services:      'Paslaugos',
    nav_products:      'Produktai',
    nav_shop:          'Parduotuvė',
    nav_cart:          'Krepšelis',
    nav_about:         'Apie mus',
    nav_portfolio:     'Darbai',
    nav_reviews:       'Atsiliepimai',
    nav_book:          'Rezervuoti',
    hero_badge:        'Profesionali grožio studija',
    hero_title_1:      'Tavo',
    hero_title_2:      'grožis —',
    hero_title_3:      'mūsų rūpestis',
    hero_sub:          'Blakstienų priauginimas, laminavimas ir viso kūno depiliacija. Profesionaliai. Švelnus pojūtis. Aukštas rezultatas.',
    hero_cta1:         'Registruotis procedūrai',
    hero_cta2:         'Peržiūrėti darbus',
    stat_clients:      'Patenkintų klientių',
    stat_years:        'Metų patirtis',
    stat_procedures:   'Procedūrų per metus',
    services_label:    'Mūsų paslaugos',
    services_title:    'Procedūros ir kainoraštis',
    services_sub:      'Visi laikai ir kainos. Pasirink paslaugą ir registruokis iš karto.',
    cat_depil_name:    'Depiliacija',
    cat_depil_sub:     'Cukrumi arba vašku · vienintelė mieste cukraus pasta',
    cat_lash_name:     'Blakstienos',
    cat_lash_sub:      'Priauginimas, papildymai ir laminavimas',
    sub_face:          'Veidas',
    sub_legs:          'Kojos',
    sub_arms:          'Rankos',
    sub_bikini:        'Bikini',
    sub_underarms:     'Pažastys',
    sub_lash_new:      'Priauginimas',
    sub_lash_refill:   'Papildymai',
    sub_lash_lam:      'Laminavimas',
    srv_face_lip:      'Viršutinė lūpa',
    srv_face_brow:     'Antakiai',
    srv_face_chin:     'Smakras',
    srv_face_cheek:    'Skruostai',
    srv_face_full:     'Visas veidas',
    srv_legs_full:     'Kojos pilnai',
    srv_legs_half:     'Kojos iki kelių (pusė)',
    srv_legs_upper:    'Kojos virš kelių',
    srv_arms_full:     'Rankos pilnai',
    srv_arms_half:     'Rankos iki alkūnių',
    srv_bikini_line:   'Bikini linija',
    srv_bikini_brazil: 'Braziliškas bikini',
    srv_underarms:     'Pažastys',
    srv_lash_classic:  'Klasikinis priauginimas',
    srv_lash_volume:   'Volume priauginimas',
    srv_lash_2_3:      'Po 2–3 savaičių',
    srv_lash_3_4:      'Po 3–4 savaičių',
    srv_lash_4_5:      'Po 4–5 savaičių',
    srv_lash_lamination: 'Blakstienų laminavimas',
    opt_g_face:        'Depiliacija — Veidas',
    opt_g_legs:        'Depiliacija — Kojos',
    opt_g_arms:        'Depiliacija — Rankos',
    opt_g_bikini:      'Depiliacija — Bikini',
    opt_g_underarms:   'Depiliacija — Pažastys',
    opt_g_lash_new:    'Blakstienos — Priauginimas',
    opt_g_lash_refill: 'Blakstienos — Papildymai',
    opt_g_lash_lam:    'Blakstienos — Laminavimas',
    book_btn:          'Rezervuoti',
    products_label:    'Produktai',
    products_title:    'Profesionali priežiūra namuose',
    products_sub:      'Kruopščiai atrinkti produktai, kurie pratęsia procedūros efektą. Pilnas asortimentas — netrukus.',
    products_tag:      'Netrukus',
    prod1_title:       'Blakstienų priežiūrai',
    prod1_desc:        'Šepetėliai, valikliai ir serumai blakstienų priauginimui prižiūrėti.',
    prod2_title:       'Po depiliacijos',
    prod2_desc:        'Drėkinantys aliejai ir kremai jautriai odai po procedūros.',
    prod3_title:       'Veido priežiūrai',
    prod3_desc:        'Profesionalios serijos kremai, serumai ir kaukės kasdienei priežiūrai.',
    products_cta_text: 'Domina konkretus produktas? Parašyk — pakonsultuosiu ir pasakysiu turimas atsargas.',
    products_cta_btn:  'Susisiekti dėl produktų',
    about_label:       'Apie mane',
    about_title:       'Labas, mieloji ✨',
    about_p1:          'Jei jau esi čia, vadinasi skiri laiko sau ir savo grožiui. Labai džiaugiuosi, kad užsukai. Esu Akvilė — profesionali grožio specialistė, dirbanti su viso kūno depiliacijomis cukrumi (vienintelė mieste), vašku, blakstienų priauginimu bei laminavimu.',
    about_p2:          'Mano tikslas — ne tik gražus rezultatas, bet ir tai, kad jaustumeisi pasitikinti savimi. Kiekviena procedūra ir kiekvienas produktas mano studijoje yra kruopščiai atrinktas, kad suteiktų matomus rezultatus ir malonią patirtį. Tu tikrai esi gerose rankose.',
    about_li1:         '10 metų patirtis nuo 2016 m.',
    about_li2:         'Vienintelė mieste cukraus depiliacija',
    about_li3:         'Kruopščiai atrinkti produktai',
    about_li4:         'Asmeninis dėmesys kiekvienai klientei',
    about_cta:         'Rezervuoti vizitą',
    whyus_label:       'Kodėl mes',
    whyus_title:       'Jūsų pasirinkimas — teisingas',
    whyus_sub:         'Akva Studio — tai kokybė, profesionalumas ir jūsų grožis mūsų rankose.',
    why1_t:            'Profesionalumas',
    why1_d:            'Nuolat mokomės ir tobulėjame. Tik sertifikuotos technikės.',
    why2_t:            'Kokybė',
    why2_d:            'Naudojame tik patikrintas, aukštos kokybės medžiagas.',
    why3_t:            'Komfortas',
    why3_d:            'Šilta, jauki aplinka. Jautiesi kaip namuose.',
    why4_t:            'Unikalumas',
    why4_d:            'Vienintelė cukraus pasta depiliacija jūsų mieste.',
    portfolio_label:   'Mūsų darbai',
    portfolio_title:   'Rezultatai kalba patys',
    portfolio_sub:     'Tikri darbai. Tikri rezultatai. Tikros klientės.',
    reviews_label:     'Atsiliepimai',
    reviews_title:     'Ką sako klientės',
    rev1_text:         'Labai profesionali studija! Blakstienų priauginimas liko 4 savaites. Tikrai grįšiu.',
    rev1_name:         'Laura K.',
    rev1_sub:          'Blakstienų priauginimas',
    rev2_text:         'Cukraus pasta depiliacija — pirmą kartą gyvenime taip neskaudėjo. Rekomenduoju visoms!',
    rev2_name:         'Monika P.',
    rev2_sub:          'Depiliacija',
    rev3_text:         'Akvilė labai kruopšti ir maloni. Studija jauki. Grįžtu kiekvieną mėnesį.',
    rev3_name:         'Gintarė S.',
    rev3_sub:          'Nuolatinė klientė',
    rev4_text:         'Geriausias blakstienų laminavimas iš visų patirtų! Akvilė labai kruopšti ir rami. Rekomenduoju iš visos širdies.',
    rev4_name:         'Janne H.',
    rev4_sub:          'Blakstienų laminavimas',
    rev5_text:         'Cukraus depiliacija buvo daug mažiau skausminga nei vašku. Oda po procedūros lygi ir rami. Tikrai grįšiu!',
    rev5_name:         'Marie L.',
    rev5_sub:          'Cukraus depiliacija',
    rev6_text:         'Mano blakstienos atrodo natūraliai ir tankiai. Studija jauki, o Akvilė — tikra profesionalė.',
    rev6_name:         'Anita B.',
    rev6_sub:          'Blakstienų priauginimas',
    booking_label:     'Registracija',
    booking_title:     'Rezervuokite savo vizitą',
    book_f1:           'Rezervacija realiu laiku',
    book_f2:           'Automatinis patvirtinimas el. paštu',
    book_f3:           'Galima atšaukti ar perkelti vizitą',
    booking_fallback:  'Nepavyksta rezervuoti? Parašykite',
    booking_open_full: 'Atidaryti rezervaciją naujame lange',
    portfolio_cap_1:   'Prieš · Po',
    portfolio_cap_2:   'Antakiai · Blakstienos',
    portfolio_cap_3:   'Volume priauginimas',
    portfolio_cap_4:   'Klasikinis priauginimas',
    portfolio_cap_5:   'Depiliacija · Prieš · Po',
    portfolio_cap_video: 'Procedūros akimirka',
    form_name:         'Vardas',
    form_phone:        'Telefono numeris',
    form_service:      'Paslauga',
    form_service_def:  'Pasirinkite paslaugą',
    form_msg:          'Pageidavimai (neprivaloma)',
    form_submit:       'Siųsti užklausą',
    form_note:         'Susisieksime per 24 val. · akvastudio75@gmail.com',
    form_success:      '✓ Ačiū! Jūsų užklausa gauta. Susisieksime per 24 val.',
    footer_about:      'Profesionali grožio studija. Blakstienų priauginimas, laminavimas, depiliacija.',
    footer_nav_t:      'Navigacija',
    footer_contact_t:  'Kontaktai',
    footer_legal_t:    'Teisinė informacija',
    footer_legal_priv: 'Privatumo politika',
    footer_legal_cookies: 'Slapukų politika',
    footer_legal_terms: 'Naudojimo sąlygos',
    footer_legal_rules: 'Naudojimosi taisyklės',
    footer_impressum_label: 'Atsakingas asmuo:',
    footer_impressum_person: '[ATSAKINGAS ASMUO]',
    footer_impressum_phone: '[TELEFONAS]',
    footer_copy:       '© 2025 Akva Studio. Visos teisės saugomos.',

    // ── LEGAL · Privatumo politika ──
    legal_priv_meta_title: 'Privatumo politika — Akva Studio',
    legal_priv_eyebrow: 'Privatumo politika',
    legal_priv_title:   'Privatumo politika',
    legal_priv_updated: 'Paskutinį kartą atnaujinta: [DATA]',
    legal_priv_h_intro: '1. Įvadas',
    legal_priv_p_intro: 'Ši privatumo politika nustato, kaip [ĮMONĖS PAVADINIMAS] (toliau — „Akva Studio", „mes") renka, naudoja ir saugo jūsų asmens duomenis, kai naudojatės mūsų svetaine [DOMAIN], rezervuojate procedūras ar perkate produktus. Mes gerbiame jūsų privatumą ir laikomės Bendrojo duomenų apsaugos reglamento (BDAR / GDPR) bei Norvegijos asmens duomenų apsaugos įstatymo reikalavimų.',
    legal_priv_h_controller: '2. Duomenų valdytojas',
    legal_priv_p_controller: 'Duomenų valdytojas: [ĮMONĖS PAVADINIMAS] · Adresas: [ADRESAS] · Įmonės kodas: [ĮMONĖS KODAS] · El. paštas: akvastudio75@gmail.com · Telefonas: [TELEFONAS] · Atsakingas asmuo: [ATSAKINGAS ASMUO]',
    legal_priv_h_data:  '3. Kokius duomenis renkame',
    legal_priv_p_data_intro: 'Renkame tik tuos duomenis, kurie būtini paslaugoms teikti:',
    legal_priv_li_data_1: 'Kontaktiniai duomenys — vardas, telefono numeris, el. paštas (registracijos formoje).',
    legal_priv_li_data_2: 'Rezervacijos duomenys — pasirinkta paslauga, data, laikas, pageidavimai (per Setmore platformą).',
    legal_priv_li_data_3: 'Pirkimo duomenys — užsakymo informacija, pristatymo adresas, mokėjimo detalės (apdorojami per mokėjimų teikėją; mes nesaugome kortelės duomenų).',
    legal_priv_li_data_4: 'Techniniai duomenys — IP adresas, naršyklės tipas, slapukai (žr. Slapukų politiką).',
    legal_priv_link_cookies: 'Slapukų politiką',
    legal_priv_h_purpose: '4. Tikslai ir teisinis pagrindas',
    legal_priv_li_purpose_1: 'Paslaugų teikimas ir rezervacijos — sutarties vykdymas (BDAR 6 str. 1 d. b p.).',
    legal_priv_li_purpose_2: 'Komunikacija dėl užklausų — teisėtas interesas atsakyti į jūsų klausimus (BDAR 6 str. 1 d. f p.).',
    legal_priv_li_purpose_3: 'Apskaitos ir teisinių pareigų vykdymas — teisinė prievolė (BDAR 6 str. 1 d. c p.).',
    legal_priv_li_purpose_4: 'Svetainės veikimas ir saugumas — teisėtas interesas (BDAR 6 str. 1 d. f p.).',
    legal_priv_h_share: '5. Kam perduodami duomenys',
    legal_priv_p_share_intro: 'Jūsų duomenys gali būti perduoti šiems duomenų tvarkytojams:',
    legal_priv_li_share_1: 'Setmore — rezervacijų sistema (Setmore Inc., JAV).',
    legal_priv_li_share_2: 'Formspree — kontaktų formos apdorojimas (Formspree Inc., JAV).',
    legal_priv_li_share_3: 'Vercel — svetainės talpinimas (Vercel Inc., JAV).',
    legal_priv_li_share_4: 'Sanity — produktų katalogo CMS (Sanity.io AS, Norvegija).',
    legal_priv_li_share_5: 'Google — Google Fonts paslaugos.',
    legal_priv_p_share_outro: 'Duomenys gali būti perduodami už ES/EEE ribų. Tokiais atvejais užtikriname tinkamas apsaugos priemones (Standard Contractual Clauses).',
    legal_priv_h_retention: '6. Saugojimo terminai',
    legal_priv_li_retention_1: 'Rezervacijos duomenys — 3 metai nuo paskutinio vizito.',
    legal_priv_li_retention_2: 'Pirkimo duomenys — 10 metų (apskaitos teisės aktų reikalavimas).',
    legal_priv_li_retention_3: 'Kontaktinės užklausos — 1 metai nuo paskutinio susirašinėjimo.',
    legal_priv_li_retention_4: 'Techniniai logai — iki 90 dienų.',
    legal_priv_h_rights: '7. Jūsų teisės',
    legal_priv_p_rights_intro: 'Pagal BDAR jūs turite teisę:',
    legal_priv_li_rights_1: 'Susipažinti su savo duomenimis ir gauti jų kopiją.',
    legal_priv_li_rights_2: 'Reikalauti ištaisyti netikslius duomenis.',
    legal_priv_li_rights_3: 'Reikalauti ištrinti duomenis („teisė būti pamirštam").',
    legal_priv_li_rights_4: 'Apriboti duomenų tvarkymą.',
    legal_priv_li_rights_5: 'Perkelti duomenis kitam paslaugų teikėjui.',
    legal_priv_li_rights_6: 'Nesutikti su duomenų tvarkymu, paremtu teisėtu interesu.',
    legal_priv_li_rights_7: 'Pateikti skundą priežiūros institucijai (Lietuvoje — Valstybinė duomenų apsaugos inspekcija; Norvegijoje — Datatilsynet).',
    legal_priv_p_rights_contact: 'Norėdami pasinaudoti šiomis teisėmis, susisiekite el. paštu akvastudio75@gmail.com. Atsakysime per 30 kalendorinių dienų.',
    legal_priv_h_security: '8. Duomenų saugumas',
    legal_priv_p_security: 'Taikome technines ir organizacines priemones, užtikrinančias duomenų konfidencialumą ir vientisumą: HTTPS šifravimą, prieigos kontrolę, reguliarius atsarginius kopijavimus. Tačiau jokia perdavimo internetu sistema negali būti 100% saugi — naudokitės atsakingai.',
    legal_priv_h_changes: '9. Politikos pakeitimai',
    legal_priv_p_changes: 'Mes galime atnaujinti šią politiką. Apie reikšmingus pakeitimus informuosime svetainėje arba el. paštu. Naujausią versiją visada rasite šiame puslapyje.',
    legal_priv_h_contact: '10. Susisiekite',
    legal_priv_p_contact: 'Klausimai dėl privatumo: akvastudio75@gmail.com',

    // ── LEGAL · Slapukų politika ──
    legal_cook_meta_title: 'Slapukų politika — Akva Studio',
    legal_cook_eyebrow: 'Slapukų politika',
    legal_cook_title:   'Slapukų politika',
    legal_cook_updated: 'Paskutinį kartą atnaujinta: [DATA]',
    legal_cook_h_what:  '1. Kas yra slapukai',
    legal_cook_p_what:  'Slapukai (angl. „cookies") — tai maži tekstiniai failai, kuriuos jūsų naršyklė išsaugo įrenginyje, kai lankotės svetainėje. Jie padeda svetainei atsiminti jūsų pasirinkimus (pvz., kalbą), užtikrinti veikimą ir pagerinti naudotojo patirtį.',
    legal_cook_h_use:   '2. Kaip naudojame slapukus',
    legal_cook_p_use:   'Akva Studio svetainė naudoja minimalų slapukų ir vietinės atminties (localStorage) kiekį, reikalingą tik svetainės veikimui. Mes nenaudojame reklamos ar trečiųjų šalių analitikos slapukų.',
    legal_cook_h_types: '3. Slapukų tipai',
    legal_cook_h_essential: '3.1. Būtini (essential)',
    legal_cook_p_essential: 'Šie slapukai/raktai būtini svetainės veikimui ir nereikalauja sutikimo:',
    legal_cook_th_name: 'Pavadinimas',
    legal_cook_th_purpose: 'Paskirtis',
    legal_cook_th_duration: 'Galiojimas',
    legal_cook_td_lang: 'Naudotojo pasirinktos kalbos (LT/EN/NO) atmintis (localStorage).',
    legal_cook_td_cart: 'Pirkinių krepšelio turinys (localStorage). Saugomas tik jūsų naršyklėje.',
    legal_cook_td_persistent: 'Iki ištrynimo',
    legal_cook_h_third: '3.2. Trečiųjų šalių paslaugos',
    legal_cook_p_third: 'Kai lankotės šių paslaugų srityse, gali būti naudojami papildomi slapukai pagal jų politikas:',
    legal_cook_li_third_1: 'Setmore — rezervacijos puslapis.',
    legal_cook_li_third_2: 'Google Fonts — šriftų užkrovimas.',
    legal_cook_li_third_3: 'Vercel — talpinimas. Gali naudoti techninius slapukus saugumui.',
    legal_cook_h_manage: '4. Kaip valdyti slapukus',
    legal_cook_p_manage_intro: 'Galite ištrinti arba blokuoti slapukus naršyklės nustatymuose. Atminkite — kai kurios funkcijos (pvz., kalbos pasirinkimas, krepšelis) gali nebeveikti.',
    legal_cook_li_manage_1: 'Chrome',
    legal_cook_li_manage_2: 'Firefox',
    legal_cook_li_manage_3: 'Safari',
    legal_cook_li_manage_4: 'Edge',
    legal_cook_h_changes: '5. Politikos pakeitimai',
    legal_cook_p_changes: 'Slapukų sąrašas gali keistis. Naujausią versiją visada rasite šiame puslapyje.',
    legal_cook_h_contact: '6. Susisiekite',
    legal_cook_p_contact: 'Klausimai dėl slapukų: akvastudio75@gmail.com. Plačiau apie duomenų tvarkymą — Privatumo politika.',
    legal_cook_link_priv: 'Privatumo politika',

    // ── LEGAL · Naudojimo sąlygos ──
    legal_terms_meta_title: 'Naudojimo sąlygos — Akva Studio',
    legal_terms_eyebrow: 'Naudojimo sąlygos',
    legal_terms_title:   'Naudojimo sąlygos ir pirkimo taisyklės',
    legal_terms_updated: 'Paskutinį kartą atnaujinta: [DATA]',
    legal_terms_h_general: '1. Bendrosios nuostatos',
    legal_terms_p_general: 'Šios naudojimo sąlygos (toliau — „Sąlygos") nustato santykius tarp [ĮMONĖS PAVADINIMAS] (toliau — „Akva Studio") ir svetainės [DOMAIN] lankytojo / kliento. Naudodamiesi svetaine, rezervuodami procedūras ar pirkdami produktus, jūs sutinkate su šiomis Sąlygomis.',
    legal_terms_h_seller: '2. Pardavėjas',
    legal_terms_p_seller: '[ĮMONĖS PAVADINIMAS] · Adresas: [ADRESAS] · Įmonės kodas: [ĮMONĖS KODAS] · PVM kodas: [PVM KODAS] · El. paštas: akvastudio75@gmail.com · Telefonas: [TELEFONAS]',
    legal_terms_h_services: '3. Procedūrų rezervacija',
    legal_terms_li_serv_1: 'Procedūras galite rezervuoti per Setmore platformą arba kontaktų formą.',
    legal_terms_li_serv_2: 'Po rezervacijos gausite patvirtinimą el. paštu.',
    legal_terms_li_serv_3: 'Procedūros kainos ir trukmė nurodytos svetainėje. Galutinę kainą patvirtina specialistas atvykus.',
    legal_terms_li_serv_4: 'Atsakomybė už pateiktus duomenis (vardas, telefono nr., el. paštas) tenka klientui.',
    legal_terms_h_cancel: '4. Vizitų atšaukimas ir perkėlimas',
    legal_terms_li_cancel_1: 'Vizitą atšaukti ar perkelti galite ne vėliau kaip prieš 24 val. — be jokio mokesčio.',
    legal_terms_li_cancel_2: 'Vėlavimas daugiau kaip 15 min. gali lemti procedūros sutrumpinimą arba atšaukimą.',
    legal_terms_li_cancel_3: 'Pakartotinai neatvykus be įspėjimo Akva Studio pasilieka teisę atsisakyti aptarnauti.',
    legal_terms_h_payment: '5. Apmokėjimas',
    legal_terms_li_pay_1: 'Procedūros apmokamos vietoje grynaisiais arba banko kortele.',
    legal_terms_li_pay_2: 'Produktų užsakymai apmokami internetu per saugų mokėjimų teikėją. Akva Studio nesaugo kortelės duomenų.',
    legal_terms_li_pay_3: 'Visos kainos nurodytos su PVM (jei taikomas).',
    legal_terms_h_delivery: '6. Produktų pristatymas',
    legal_terms_li_del_1: 'Pristatymo terminai ir kainos nurodomos užsakymo metu.',
    legal_terms_li_del_2: 'Užsakymai apdorojami per 1–3 darbo dienas.',
    legal_terms_li_del_3: 'Atsiimti vietoje galima nemokamai (susitarus iš anksto).',
    legal_terms_h_returns: '7. Grąžinimai ir keitimai',
    legal_terms_p_returns_intro: 'Pagal Lietuvos / Norvegijos vartotojų teisių aktus:',
    legal_terms_li_ret_1: 'Nepatikusią prekę galite grąžinti per 14 dienų nuo gavimo, jei ji nenaudota ir originaliame įpakavime.',
    legal_terms_li_ret_2: 'Higienos produktai (kosmetika su pažeistu apsauginiu sluoksniu, atidarytos pakuotės) — negrąžinami pagal įstatymą.',
    legal_terms_li_ret_3: 'Defektines prekes keičiame nemokamai. Susisiekite per 14 dienų nuo trūkumo aptikimo.',
    legal_terms_li_ret_4: 'Grąžinimo siuntimo išlaidos tenka klientui, nebent prekė turi defektą.',
    legal_terms_p_returns_outro: 'Kreipkitės: akvastudio75@gmail.com',
    legal_terms_h_responsibility: '8. Atsakomybė',
    legal_terms_li_resp_1: 'Klientas privalo informuoti specialistą apie alergijas, kontraindikacijas ir sveikatos sutrikimus prieš procedūrą.',
    legal_terms_li_resp_2: 'Akva Studio neatsako už reakcijas, kurių priežastis — neatskleista informacija.',
    legal_terms_li_resp_3: 'Svetainės turinys teikiamas „kaip yra"; siekiame tikslumo, bet negarantuojame nepertraukiamo veikimo.',
    legal_terms_h_ip: '9. Intelektinė nuosavybė',
    legal_terms_p_ip: 'Visas svetainės turinys (tekstai, nuotraukos, video, logotipas, dizainas) priklauso Akva Studio arba jo licencijos davėjams. Be raštiško leidimo draudžiama kopijuoti, platinti ar naudoti komerciniams tikslams.',
    legal_terms_h_law: '10. Taikoma teisė ir ginčai',
    legal_terms_p_law: 'Šios Sąlygos reglamentuojamos pagal [ŠALIES] teisę. Ginčai sprendžiami derybų keliu, o nesusitarus — kompetentingame teisme pagal pardavėjo registracijos vietą. Vartotojas taip pat gali kreiptis į ES interneto ginčų sprendimo platformą.',
    legal_terms_h_changes: '11. Sąlygų pakeitimai',
    legal_terms_p_changes: 'Akva Studio gali keisti šias Sąlygas. Galioja ta versija, kuri buvo paskelbta užsakymo / rezervacijos metu.',
    legal_terms_h_contact: '12. Susisiekite',
    legal_terms_p_contact: 'Klausimai dėl sąlygų: akvastudio75@gmail.com. Taip pat žr. Privatumo politiką ir Slapukų politiką.',
    legal_terms_link_priv: 'Privatumo politiką',
    legal_terms_link_cookies: 'Slapukų politiką',

    // ── LEGAL · Naudojimosi taisyklės ──
    legal_rules_meta_title: 'Naudojimosi taisyklės — Akva Studio',
    legal_rules_eyebrow: 'Naudojimosi taisyklės',
    legal_rules_title:   'Naudojimosi taisyklės',
    legal_rules_updated: 'Paskutinį kartą atnaujinta: [DATA]',
    legal_rules_h_scope: '1. Taikymo sritis',
    legal_rules_p_scope: 'Šios taisyklės nustato Akva Studio svetainės [DOMAIN] naudojimo tvarką. Naudodamiesi svetaine, jūs sutinkate jų laikytis. Jei nesutinkate — prašome svetaine nesinaudoti.',
    legal_rules_p_scope_note: 'Taisyklės papildo mūsų Naudojimo sąlygas ir pirkimo taisykles, Privatumo politiką ir Slapukų politiką.',
    legal_rules_link_terms: 'Naudojimo sąlygas ir pirkimo taisykles',
    legal_rules_link_priv: 'Privatumo politiką',
    legal_rules_link_cookies: 'Slapukų politiką',
    legal_rules_h_access: '2. Prieiga prie svetainės',
    legal_rules_li_access_1: 'Svetainė pasiekiama 24/7, tačiau galimi laikini sutrikimai dėl techninių darbų ar nepriklausomų aplinkybių.',
    legal_rules_li_access_2: 'Akva Studio neįsipareigoja užtikrinti nepertraukiamo, klaidų neturinčio veikimo.',
    legal_rules_li_access_3: 'Mes pasiliekame teisę bet kada keisti, sustabdyti ar nutraukti svetainės veikimą be išankstinio įspėjimo.',
    legal_rules_h_user: '3. Naudotojo pareigos',
    legal_rules_p_user_intro: 'Naudodamiesi svetaine, jūs įsipareigojate:',
    legal_rules_li_user_1: 'Pateikti tikslią ir teisingą informaciją (rezervuojant ar perkant).',
    legal_rules_li_user_2: 'Naudoti svetainę tik teisėtais tikslais.',
    legal_rules_li_user_3: 'Negadinti ir netrikdyti svetainės veikimo.',
    legal_rules_li_user_4: 'Gerbti kitų naudotojų ir Akva Studio teises.',
    legal_rules_li_user_5: 'Saugoti savo prisijungimo duomenis (jei tokie yra) ir nedalintis jais su trečiosiomis šalimis.',
    legal_rules_h_prohibited: '4. Draudžiama veikla',
    legal_rules_p_prohibited_intro: 'Naudodamiesi svetaine jūs negalite:',
    legal_rules_li_prohibited_1: 'Bandyti įsilaužti, skenuoti ar kitaip pažeisti svetainės saugumą.',
    legal_rules_li_prohibited_2: 'Naudoti automatinių priemonių (botų, scraperių, crawlerių) be raštiško sutikimo.',
    legal_rules_li_prohibited_3: 'Įkelti ar siųsti virusus, kenkėjišką kodą arba bet kokį žalingą turinį.',
    legal_rules_li_prohibited_4: 'Pateikti melagingą informaciją ar apsimesti kitu asmeniu.',
    legal_rules_li_prohibited_5: 'Rinkti kitų naudotojų duomenis be jų sutikimo.',
    legal_rules_li_prohibited_6: 'Naudoti svetainę reklamai, šlamštui (spam) ar komerciniams tikslams be leidimo.',
    legal_rules_li_prohibited_7: 'Kopijuoti, modifikuoti ar platinti svetainės turinį be raštiško sutikimo.',
    legal_rules_li_prohibited_8: 'Apeiti ar bandyti apeiti technines apsaugos priemones.',
    legal_rules_h_content: '5. Naudotojo turinys',
    legal_rules_p_content: 'Jei svetainėje pateikiate atsiliepimus, komentarus ar kitokį turinį, suteikiate Akva Studio neišimtinę, neribotos trukmės teisę jį naudoti, redaguoti ir publikuoti rinkodaros tikslais. Jūs atsakote už pateikto turinio tikslumą ir teisėtumą.',
    legal_rules_p_content_remove: 'Akva Studio pasilieka teisę be įspėjimo pašalinti turinį, kuris pažeidžia šias taisykles, įstatymus arba trečiųjų šalių teises.',
    legal_rules_h_ip: '6. Intelektinė nuosavybė',
    legal_rules_p_ip: 'Visas svetainės turinys (tekstai, nuotraukos, video, logotipas, grafika, dizainas, kodas) priklauso Akva Studio arba jo licencijos davėjams ir yra saugomas autorių teisių ir kitų intelektinės nuosavybės įstatymų. Jūs galite turinį peržiūrėti asmeniniam, nekomerciniam naudojimui.',
    legal_rules_p_ip_brand: 'Pavadinimas „Akva Studio", logotipas ir vizualinis identitetas yra saugomi prekės ženklai. Jų naudojimas be raštiško sutikimo draudžiamas.',
    legal_rules_h_links: '7. Nuorodos į trečiųjų šalių svetaines',
    legal_rules_p_links: 'Svetainėje gali būti nuorodų į trečiųjų šalių svetaines (pvz., Setmore, Sanity, socialiniai tinklai). Akva Studio neatsako už šių svetainių turinį, privatumo praktiką ar veikimą. Lankydamiesi jose, susipažinkite su jų taisyklėmis.',
    legal_rules_h_liability: '8. Atsakomybės apribojimas',
    legal_rules_li_liability_1: 'Svetainės turinys teikiamas „kaip yra" be jokių garantijų.',
    legal_rules_li_liability_2: 'Akva Studio neatsako už netiesioginę, atsitiktinę ar pasekminę žalą, atsiradusią dėl svetainės naudojimo.',
    legal_rules_li_liability_3: 'Mes neatsakome už duomenų praradimą, įrenginio gedimus ar kitas problemas, kilusias dėl svetainės naudojimo.',
    legal_rules_li_liability_4: 'Šie apribojimai netaikomi tais atvejais, kai įstatymai jų netoleruoja.',
    legal_rules_h_consequences: '9. Taisyklių pažeidimo pasekmės',
    legal_rules_p_consequences: 'Pažeidus šias taisykles, Akva Studio pasilieka teisę:',
    legal_rules_li_consequences_1: 'Apriboti ar nutraukti prieigą prie svetainės.',
    legal_rules_li_consequences_2: 'Pašalinti su pažeidimu susijusį turinį.',
    legal_rules_li_consequences_3: 'Reikalauti atlyginti žalą įstatymų nustatyta tvarka.',
    legal_rules_li_consequences_4: 'Kreiptis į teisėsaugos institucijas, jei pažeidimas yra teisės akto pažeidimas.',
    legal_rules_h_law: '10. Taikoma teisė',
    legal_rules_p_law: 'Šios taisyklės reglamentuojamos pagal [ŠALIES] teisę. Ginčai sprendžiami derybų keliu, o nesusitarus — kompetentingame teisme pagal pardavėjo registracijos vietą.',
    legal_rules_h_changes: '11. Taisyklių pakeitimai',
    legal_rules_p_changes: 'Akva Studio gali keisti šias taisykles. Naujausia versija visada skelbiama šiame puslapyje. Toliau naudodamiesi svetaine po pakeitimų jūs sutinkate su atnaujinta versija.',
    legal_rules_h_contact: '12. Susisiekite',
    legal_rules_p_contact: 'Klausimai dėl naudojimosi taisyklių: akvastudio75@gmail.com',
  },
  en: {
    nav_services:      'Services',
    nav_products:      'Products',
    nav_shop:          'Shop',
    nav_cart:          'Cart',
    nav_about:         'About',
    nav_portfolio:     'Portfolio',
    nav_reviews:       'Reviews',
    nav_book:          'Book Now',
    hero_badge:        'Professional beauty studio',
    hero_title_1:      'Your',
    hero_title_2:      'beauty —',
    hero_title_3:      'our care',
    hero_sub:          'Lash extensions, lash lamination and full-body hair removal. Professional. Gentle. High results.',
    hero_cta1:         'Book a procedure',
    hero_cta2:         'View our work',
    stat_clients:      'Happy clients',
    stat_years:        'Years experience',
    stat_procedures:   'Procedures / year',
    services_label:    'Our services',
    services_title:    'Services & price list',
    services_sub:      'All durations and prices. Pick a service and book directly.',
    cat_depil_name:    'Hair Removal',
    cat_depil_sub:     'Sugar paste or wax · the only sugar paste in town',
    cat_lash_name:     'Lashes',
    cat_lash_sub:      'Extensions, refills and lamination',
    sub_face:          'Face',
    sub_legs:          'Legs',
    sub_arms:          'Arms',
    sub_bikini:        'Bikini',
    sub_underarms:     'Underarms',
    sub_lash_new:      'Extensions',
    sub_lash_refill:   'Refills',
    sub_lash_lam:      'Lamination',
    srv_face_lip:      'Upper lip',
    srv_face_brow:     'Eyebrows',
    srv_face_chin:     'Chin',
    srv_face_cheek:    'Cheeks',
    srv_face_full:     'Full face',
    srv_legs_full:     'Full legs',
    srv_legs_half:     'Lower legs (half)',
    srv_legs_upper:    'Upper legs',
    srv_arms_full:     'Full arms',
    srv_arms_half:     'Forearms',
    srv_bikini_line:   'Bikini line',
    srv_bikini_brazil: 'Brazilian bikini',
    srv_underarms:     'Underarms',
    srv_lash_classic:  'Classic extensions',
    srv_lash_volume:   'Volume extensions',
    srv_lash_2_3:      'After 2–3 weeks',
    srv_lash_3_4:      'After 3–4 weeks',
    srv_lash_4_5:      'After 4–5 weeks',
    srv_lash_lamination: 'Lash lamination',
    opt_g_face:        'Hair Removal — Face',
    opt_g_legs:        'Hair Removal — Legs',
    opt_g_arms:        'Hair Removal — Arms',
    opt_g_bikini:      'Hair Removal — Bikini',
    opt_g_underarms:   'Hair Removal — Underarms',
    opt_g_lash_new:    'Lashes — Extensions',
    opt_g_lash_refill: 'Lashes — Refills',
    opt_g_lash_lam:    'Lashes — Lamination',
    book_btn:          'Book',
    products_label:    'Products',
    products_title:    'Professional care at home',
    products_sub:      'Carefully selected products that extend the effect of your treatment. Full range — coming soon.',
    products_tag:      'Coming soon',
    prod1_title:       'Lash care',
    prod1_desc:        'Brushes, cleansers and serums to care for lash extensions.',
    prod2_title:       'After depilation',
    prod2_desc:        'Moisturising oils and creams for sensitive skin after treatment.',
    prod3_title:       'Facial care',
    prod3_desc:        'Professional-grade creams, serums and masks for daily care.',
    products_cta_text: 'Interested in a specific product? Write to me — I will advise and tell you what is in stock.',
    products_cta_btn:  'Contact about products',
    about_label:       'About me',
    about_title:       'Hello, lovely ✨',
    about_p1:          'If you are here, it means you take time for yourself and your beauty. I am so glad you stopped by. I am Akvilė — a professional beauty specialist working with full-body sugar depilation (the only one in town), waxing, lash extensions and lamination.',
    about_p2:          'My goal is not only a beautiful result, but also that you feel confident in yourself. Every procedure and every product in my studio is carefully selected to deliver visible results and a pleasant experience. You are truly in good hands.',
    about_li1:         '10 years of experience since 2016',
    about_li2:         'The only sugar depilation in town',
    about_li3:         'Carefully selected products',
    about_li4:         'Personal attention to every client',
    about_cta:         'Book a visit',
    whyus_label:       'Why us',
    whyus_title:       'Your choice is right',
    whyus_sub:         'Akva Studio — quality, professionalism and your beauty in our hands.',
    why1_t:            'Professionalism',
    why1_d:            'We constantly learn and improve. Only certified technicians.',
    why2_t:            'Quality',
    why2_d:            'We use only proven, premium quality materials.',
    why3_t:            'Comfort',
    why3_d:            'Warm, cozy environment. Feel at home.',
    why4_t:            'Uniqueness',
    why4_d:            'The only sugar paste depilation in your city.',
    portfolio_label:   'Our work',
    portfolio_title:   'Results speak for themselves',
    portfolio_sub:     'Real work. Real results. Real clients.',
    reviews_label:     'Reviews',
    reviews_title:     'What clients say',
    rev1_text:         'Very professional studio! Lash extensions lasted 4 weeks. Will definitely come back.',
    rev1_name:         'Laura K.',
    rev1_sub:          'Lash Extensions',
    rev2_text:         'Sugar paste depilation — for the first time in my life it did not hurt like that. Recommend to everyone!',
    rev2_name:         'Monika P.',
    rev2_sub:          'Depilation',
    rev3_text:         'Akvilė is very thorough and pleasant. Studio is cozy. I come back every month.',
    rev3_name:         'Gintarė S.',
    rev3_sub:          'Regular client',
    rev4_text:         'Best lash lamination I have ever had! Akvilė is so precise and calm. Highly recommend.',
    rev4_name:         'Janne H.',
    rev4_sub:          'Lash Lamination',
    rev5_text:         'Sugar depilation hurt much less than wax. My skin felt smooth and calm afterwards. I will be back!',
    rev5_name:         'Marie L.',
    rev5_sub:          'Sugar Depilation',
    rev6_text:         'My lashes look so natural and full. The studio is cozy and Akvilė is a true professional.',
    rev6_name:         'Anita B.',
    rev6_sub:          'Lash Extensions',
    booking_label:     'Booking',
    booking_title:     'Book your visit',
    book_f1:           'Real-time booking',
    book_f2:           'Automatic email confirmation',
    book_f3:           'Easy to cancel or reschedule',
    booking_fallback:  'Cannot book? Email us at',
    booking_open_full: 'Open booking in new window',
    portfolio_cap_1:   'Before · After',
    portfolio_cap_2:   'Brows · Lashes',
    portfolio_cap_3:   'Volume extensions',
    portfolio_cap_4:   'Classic extensions',
    portfolio_cap_5:   'Hair removal · Before · After',
    portfolio_cap_video: 'Procedure moment',
    form_name:         'Name',
    form_phone:        'Phone number',
    form_service:      'Service',
    form_service_def:  'Select a service',
    form_msg:          'Preferences (optional)',
    form_submit:       'Send request',
    form_note:         'We will contact you within 24h · akvastudio75@gmail.com',
    form_success:      '✓ Thank you! Your request has been received. We will contact you within 24h.',
    footer_about:      'Professional beauty studio. Lash extensions, lamination, depilation.',
    footer_nav_t:      'Navigation',
    footer_contact_t:  'Contact',
    footer_legal_t:    'Legal',
    footer_legal_priv: 'Privacy Policy',
    footer_legal_cookies: 'Cookie Policy',
    footer_legal_terms: 'Terms of Use',
    footer_legal_rules: 'Website Rules',
    footer_impressum_label: 'Responsible person:',
    footer_impressum_person: '[RESPONSIBLE PERSON]',
    footer_impressum_phone: '[PHONE]',
    footer_copy:       '© 2025 Akva Studio. All rights reserved.',

    // ── LEGAL · Privacy Policy ──
    legal_priv_meta_title: 'Privacy Policy — Akva Studio',
    legal_priv_eyebrow: 'Privacy Policy',
    legal_priv_title:   'Privacy Policy',
    legal_priv_updated: 'Last updated: [DATE]',
    legal_priv_h_intro: '1. Introduction',
    legal_priv_p_intro: 'This privacy policy sets out how [COMPANY NAME] (hereinafter — "Akva Studio", "we") collects, uses and stores your personal data when you use our website [DOMAIN], book treatments or buy products. We respect your privacy and comply with the General Data Protection Regulation (GDPR) and Norwegian personal data protection law.',
    legal_priv_h_controller: '2. Data controller',
    legal_priv_p_controller: 'Data controller: [COMPANY NAME] · Address: [ADDRESS] · Company code: [COMPANY ID] · Email: akvastudio75@gmail.com · Phone: [PHONE] · Responsible person: [RESPONSIBLE PERSON]',
    legal_priv_h_data:  '3. What data we collect',
    legal_priv_p_data_intro: 'We only collect data that is necessary to provide our services:',
    legal_priv_li_data_1: 'Contact data — name, phone number, email (in the booking form).',
    legal_priv_li_data_2: 'Booking data — selected service, date, time, preferences (via the Setmore platform).',
    legal_priv_li_data_3: 'Purchase data — order details, delivery address, payment data (processed by the payment provider; we do not store card data).',
    legal_priv_li_data_4: 'Technical data — IP address, browser type, cookies (see Cookie Policy).',
    legal_priv_link_cookies: 'Cookie Policy',
    legal_priv_h_purpose: '4. Purposes and legal basis',
    legal_priv_li_purpose_1: 'Service delivery and bookings — performance of contract (GDPR art. 6(1)(b)).',
    legal_priv_li_purpose_2: 'Communication regarding inquiries — legitimate interest in answering your questions (GDPR art. 6(1)(f)).',
    legal_priv_li_purpose_3: 'Accounting and legal obligations — legal obligation (GDPR art. 6(1)(c)).',
    legal_priv_li_purpose_4: 'Website operation and security — legitimate interest (GDPR art. 6(1)(f)).',
    legal_priv_h_share: '5. Who we share data with',
    legal_priv_p_share_intro: 'Your data may be transferred to the following data processors:',
    legal_priv_li_share_1: 'Setmore — booking system (Setmore Inc., USA).',
    legal_priv_li_share_2: 'Formspree — contact form processing (Formspree Inc., USA).',
    legal_priv_li_share_3: 'Vercel — website hosting (Vercel Inc., USA).',
    legal_priv_li_share_4: 'Sanity — product catalog CMS (Sanity.io AS, Norway).',
    legal_priv_li_share_5: 'Google — Google Fonts service.',
    legal_priv_p_share_outro: 'Data may be transferred outside the EU/EEA. In such cases we ensure appropriate safeguards (Standard Contractual Clauses).',
    legal_priv_h_retention: '6. Retention periods',
    legal_priv_li_retention_1: 'Booking data — 3 years from last visit.',
    legal_priv_li_retention_2: 'Purchase data — 10 years (accounting law requirement).',
    legal_priv_li_retention_3: 'Contact inquiries — 1 year from last correspondence.',
    legal_priv_li_retention_4: 'Technical logs — up to 90 days.',
    legal_priv_h_rights: '7. Your rights',
    legal_priv_p_rights_intro: 'Under GDPR you have the right to:',
    legal_priv_li_rights_1: 'Access your data and obtain a copy.',
    legal_priv_li_rights_2: 'Rectify inaccurate data.',
    legal_priv_li_rights_3: 'Request erasure of data ("right to be forgotten").',
    legal_priv_li_rights_4: 'Restrict processing.',
    legal_priv_li_rights_5: 'Data portability.',
    legal_priv_li_rights_6: 'Object to processing based on legitimate interest.',
    legal_priv_li_rights_7: 'Lodge a complaint with the supervisory authority (in Lithuania — State Data Protection Inspectorate; in Norway — Datatilsynet).',
    legal_priv_p_rights_contact: 'To exercise these rights, contact us at akvastudio75@gmail.com. We will respond within 30 calendar days.',
    legal_priv_h_security: '8. Data security',
    legal_priv_p_security: 'We apply technical and organizational measures to ensure data confidentiality and integrity: HTTPS encryption, access control, regular backups. However, no internet transmission system can be 100% secure — use responsibly.',
    legal_priv_h_changes: '9. Policy changes',
    legal_priv_p_changes: 'We may update this policy. We will notify you of material changes on the website or by email. The latest version is always available on this page.',
    legal_priv_h_contact: '10. Contact',
    legal_priv_p_contact: 'Privacy questions: akvastudio75@gmail.com',

    // ── LEGAL · Cookie Policy ──
    legal_cook_meta_title: 'Cookie Policy — Akva Studio',
    legal_cook_eyebrow: 'Cookie Policy',
    legal_cook_title:   'Cookie Policy',
    legal_cook_updated: 'Last updated: [DATE]',
    legal_cook_h_what:  '1. What are cookies',
    legal_cook_p_what:  'Cookies are small text files that your browser stores on your device when you visit a website. They help the site remember your choices (e.g. language), ensure functionality and improve the user experience.',
    legal_cook_h_use:   '2. How we use cookies',
    legal_cook_p_use:   'The Akva Studio website uses a minimal amount of cookies and local storage (localStorage), needed only for site operation. We do not use advertising or third-party analytics cookies.',
    legal_cook_h_types: '3. Cookie types',
    legal_cook_h_essential: '3.1. Essential',
    legal_cook_p_essential: 'These cookies/keys are essential for the site to function and do not require consent:',
    legal_cook_th_name: 'Name',
    legal_cook_th_purpose: 'Purpose',
    legal_cook_th_duration: 'Duration',
    legal_cook_td_lang: 'Stores the user\'s selected language (LT/EN/NO) in localStorage.',
    legal_cook_td_cart: 'Cart contents (localStorage). Stored only in your browser.',
    legal_cook_td_persistent: 'Until cleared',
    legal_cook_h_third: '3.2. Third-party services',
    legal_cook_p_third: 'When you visit areas of these services, additional cookies may be used under their policies:',
    legal_cook_li_third_1: 'Setmore — booking page.',
    legal_cook_li_third_2: 'Google Fonts — font loading.',
    legal_cook_li_third_3: 'Vercel — hosting. May use technical cookies for security.',
    legal_cook_h_manage: '4. How to manage cookies',
    legal_cook_p_manage_intro: 'You can delete or block cookies in your browser settings. Note — some features (e.g. language selector, cart) may stop working.',
    legal_cook_li_manage_1: 'Chrome',
    legal_cook_li_manage_2: 'Firefox',
    legal_cook_li_manage_3: 'Safari',
    legal_cook_li_manage_4: 'Edge',
    legal_cook_h_changes: '5. Policy changes',
    legal_cook_p_changes: 'The cookie list may change. The latest version is always available on this page.',
    legal_cook_h_contact: '6. Contact',
    legal_cook_p_contact: 'Questions about cookies: akvastudio75@gmail.com. For more on data processing, see Privacy Policy.',
    legal_cook_link_priv: 'Privacy Policy',

    // ── LEGAL · Terms of Use ──
    legal_terms_meta_title: 'Terms of Use — Akva Studio',
    legal_terms_eyebrow: 'Terms of Use',
    legal_terms_title:   'Terms of Use and Purchase Conditions',
    legal_terms_updated: 'Last updated: [DATE]',
    legal_terms_h_general: '1. General provisions',
    legal_terms_p_general: 'These terms of use (the "Terms") govern the relationship between [COMPANY NAME] (the "Akva Studio") and the visitor / customer of [DOMAIN]. By using the site, booking treatments or buying products, you agree to these Terms.',
    legal_terms_h_seller: '2. Seller',
    legal_terms_p_seller: '[COMPANY NAME] · Address: [ADDRESS] · Company code: [COMPANY ID] · VAT code: [VAT CODE] · Email: akvastudio75@gmail.com · Phone: [PHONE]',
    legal_terms_h_services: '3. Treatment booking',
    legal_terms_li_serv_1: 'Treatments can be booked via the Setmore platform or the contact form.',
    legal_terms_li_serv_2: 'After booking you will receive a confirmation by email.',
    legal_terms_li_serv_3: 'Treatment prices and durations are listed on the website. The final price is confirmed by the specialist on arrival.',
    legal_terms_li_serv_4: 'Responsibility for the data provided (name, phone, email) lies with the customer.',
    legal_terms_h_cancel: '4. Cancellation and rescheduling',
    legal_terms_li_cancel_1: 'You may cancel or reschedule your visit no later than 24 hours in advance — free of charge.',
    legal_terms_li_cancel_2: 'Arriving more than 15 minutes late may result in shortened or cancelled treatment.',
    legal_terms_li_cancel_3: 'In case of repeated no-shows without notice, Akva Studio reserves the right to refuse service.',
    legal_terms_h_payment: '5. Payment',
    legal_terms_li_pay_1: 'Treatments are paid on site by cash or card.',
    legal_terms_li_pay_2: 'Product orders are paid online via a secure payment provider. Akva Studio does not store card data.',
    legal_terms_li_pay_3: 'All prices include VAT (where applicable).',
    legal_terms_h_delivery: '6. Product delivery',
    legal_terms_li_del_1: 'Delivery times and prices are stated at order time.',
    legal_terms_li_del_2: 'Orders are processed within 1–3 business days.',
    legal_terms_li_del_3: 'In-store pickup is free (by prior arrangement).',
    legal_terms_h_returns: '7. Returns and exchanges',
    legal_terms_p_returns_intro: 'Under Lithuanian / Norwegian consumer law:',
    legal_terms_li_ret_1: 'You may return an unwanted item within 14 days of receipt, if unused and in original packaging.',
    legal_terms_li_ret_2: 'Hygiene products (cosmetics with broken seal, opened packaging) — non-returnable by law.',
    legal_terms_li_ret_3: 'Defective items are exchanged free of charge. Contact us within 14 days of discovering the defect.',
    legal_terms_li_ret_4: 'Return shipping costs are borne by the customer, unless the item is defective.',
    legal_terms_p_returns_outro: 'Contact: akvastudio75@gmail.com',
    legal_terms_h_responsibility: '8. Liability',
    legal_terms_li_resp_1: 'The customer must inform the specialist of allergies, contraindications and health conditions before treatment.',
    legal_terms_li_resp_2: 'Akva Studio is not liable for reactions caused by undisclosed information.',
    legal_terms_li_resp_3: 'Site content is provided "as is"; we strive for accuracy but do not guarantee uninterrupted operation.',
    legal_terms_h_ip: '9. Intellectual property',
    legal_terms_p_ip: 'All website content (texts, photos, video, logo, design) belongs to Akva Studio or its licensors. Copying, distribution or commercial use without written permission is prohibited.',
    legal_terms_h_law: '10. Applicable law and disputes',
    legal_terms_p_law: 'These Terms are governed by [COUNTRY] law. Disputes are settled by negotiation, and otherwise — by the competent court at the seller\'s registered office. Consumers may also use the EU online dispute resolution platform.',
    legal_terms_h_changes: '11. Changes to terms',
    legal_terms_p_changes: 'Akva Studio may amend these Terms. The version published at the time of order / booking applies.',
    legal_terms_h_contact: '12. Contact',
    legal_terms_p_contact: 'Questions about the terms: akvastudio75@gmail.com. See also Privacy Policy and Cookie Policy.',
    legal_terms_link_priv: 'Privacy Policy',
    legal_terms_link_cookies: 'Cookie Policy',

    // ── LEGAL · Website Rules ──
    legal_rules_meta_title: 'Website Rules — Akva Studio',
    legal_rules_eyebrow: 'Website Rules',
    legal_rules_title:   'Website Rules',
    legal_rules_updated: 'Last updated: [DATE]',
    legal_rules_h_scope: '1. Scope',
    legal_rules_p_scope: 'These rules govern the use of the Akva Studio website [DOMAIN]. By using the site you agree to follow them. If you do not agree — please do not use the site.',
    legal_rules_p_scope_note: 'These rules supplement our Terms of Use and Purchase Conditions, Privacy Policy and Cookie Policy.',
    legal_rules_link_terms: 'Terms of Use and Purchase Conditions',
    legal_rules_link_priv: 'Privacy Policy',
    legal_rules_link_cookies: 'Cookie Policy',
    legal_rules_h_access: '2. Site availability',
    legal_rules_li_access_1: 'The site is available 24/7, but temporary disruptions may occur due to maintenance or external circumstances.',
    legal_rules_li_access_2: 'Akva Studio does not guarantee uninterrupted, error-free operation.',
    legal_rules_li_access_3: 'We reserve the right to change, suspend or discontinue the site at any time without prior notice.',
    legal_rules_h_user: '3. User obligations',
    legal_rules_p_user_intro: 'By using the site, you commit to:',
    legal_rules_li_user_1: 'Provide accurate and truthful information (when booking or purchasing).',
    legal_rules_li_user_2: 'Use the site only for lawful purposes.',
    legal_rules_li_user_3: 'Not damage or disrupt the site\'s operation.',
    legal_rules_li_user_4: 'Respect the rights of other users and Akva Studio.',
    legal_rules_li_user_5: 'Keep your login credentials (if any) safe and not share them with third parties.',
    legal_rules_h_prohibited: '4. Prohibited conduct',
    legal_rules_p_prohibited_intro: 'When using the site you may not:',
    legal_rules_li_prohibited_1: 'Attempt to hack, scan or otherwise breach the site\'s security.',
    legal_rules_li_prohibited_2: 'Use automated tools (bots, scrapers, crawlers) without written consent.',
    legal_rules_li_prohibited_3: 'Upload or transmit viruses, malicious code or any harmful content.',
    legal_rules_li_prohibited_4: 'Provide false information or impersonate another person.',
    legal_rules_li_prohibited_5: 'Collect data on other users without their consent.',
    legal_rules_li_prohibited_6: 'Use the site for advertising, spam or commercial purposes without permission.',
    legal_rules_li_prohibited_7: 'Copy, modify or redistribute the site\'s content without written consent.',
    legal_rules_li_prohibited_8: 'Bypass or attempt to bypass technical protection measures.',
    legal_rules_h_content: '5. User-generated content',
    legal_rules_p_content: 'If you submit reviews, comments or other content on the site, you grant Akva Studio a non-exclusive, perpetual right to use, edit and publish it for marketing purposes. You are responsible for the accuracy and lawfulness of submitted content.',
    legal_rules_p_content_remove: 'Akva Studio reserves the right to remove, without notice, content that violates these rules, the law or the rights of third parties.',
    legal_rules_h_ip: '6. Intellectual property',
    legal_rules_p_ip: 'All site content (texts, photos, video, logo, graphics, design, code) belongs to Akva Studio or its licensors and is protected by copyright and other intellectual property laws. You may view content for personal, non-commercial use.',
    legal_rules_p_ip_brand: 'The name "Akva Studio", the logo and visual identity are protected trademarks. Their use without written consent is prohibited.',
    legal_rules_h_links: '7. Links to third-party sites',
    legal_rules_p_links: 'The site may contain links to third-party sites (e.g. Setmore, Sanity, social networks). Akva Studio is not responsible for the content, privacy practices or operation of those sites. When visiting them, review their rules.',
    legal_rules_h_liability: '8. Limitation of liability',
    legal_rules_li_liability_1: 'Site content is provided "as is" without any warranties.',
    legal_rules_li_liability_2: 'Akva Studio is not liable for indirect, incidental or consequential damages arising from site use.',
    legal_rules_li_liability_3: 'We are not liable for data loss, device failures or other problems arising from site use.',
    legal_rules_li_liability_4: 'These limitations do not apply where the law does not permit them.',
    legal_rules_h_consequences: '9. Consequences of violations',
    legal_rules_p_consequences: 'In case of violation of these rules, Akva Studio reserves the right to:',
    legal_rules_li_consequences_1: 'Restrict or terminate access to the site.',
    legal_rules_li_consequences_2: 'Remove content related to the violation.',
    legal_rules_li_consequences_3: 'Seek damages under the law.',
    legal_rules_li_consequences_4: 'Refer the matter to law enforcement, if the violation breaches the law.',
    legal_rules_h_law: '10. Applicable law',
    legal_rules_p_law: 'These rules are governed by [COUNTRY] law. Disputes are settled by negotiation, and otherwise — by the competent court at the seller\'s registered office.',
    legal_rules_h_changes: '11. Rule changes',
    legal_rules_p_changes: 'Akva Studio may amend these rules. The latest version is always published on this page. Continued use of the site after changes means you accept the updated version.',
    legal_rules_h_contact: '12. Contact',
    legal_rules_p_contact: 'Questions about the website rules: akvastudio75@gmail.com',
  },
  no: {
    nav_services:      'Tjenester',
    nav_products:      'Produkter',
    nav_shop:          'Butikk',
    nav_cart:          'Handlekurv',
    nav_about:         'Om oss',
    nav_portfolio:     'Portefølje',
    nav_reviews:       'Anmeldelser',
    nav_book:          'Bestill',
    hero_badge:        'Profesjonell skjønnhetsstudio',
    hero_title_1:      'Din',
    hero_title_2:      'skjønnhet —',
    hero_title_3:      'vår omsorg',
    hero_sub:          'Vipper, vippe-laminering og hårtjerning for hele kroppen. Profesjonelt. Skånsomt. Høye resultater.',
    hero_cta1:         'Bestill en behandling',
    hero_cta2:         'Se våre arbeider',
    stat_clients:      'Fornøyde kunder',
    stat_years:        'Års erfaring',
    stat_procedures:   'Behandlinger / år',
    services_label:    'Våre tjenester',
    services_title:    'Behandlinger og prisliste',
    services_sub:      'Alle varigheter og priser. Velg behandling og bestill direkte.',
    cat_depil_name:    'Hårfjerning',
    cat_depil_sub:     'Sukkerpasta eller voks · den eneste sukkerpastaen i byen',
    cat_lash_name:     'Vipper',
    cat_lash_sub:      'Extensions, påfyll og laminering',
    sub_face:          'Ansikt',
    sub_legs:          'Bein',
    sub_arms:          'Armer',
    sub_bikini:        'Bikini',
    sub_underarms:     'Armhuler',
    sub_lash_new:      'Extensions',
    sub_lash_refill:   'Påfyll',
    sub_lash_lam:      'Laminering',
    srv_face_lip:      'Overleppe',
    srv_face_brow:     'Øyenbryn',
    srv_face_chin:     'Hake',
    srv_face_cheek:    'Kinn',
    srv_face_full:     'Hele ansiktet',
    srv_legs_full:     'Hele bein',
    srv_legs_half:     'Legger (halve bein)',
    srv_legs_upper:    'Lår',
    srv_arms_full:     'Hele armer',
    srv_arms_half:     'Underarmer',
    srv_bikini_line:   'Bikinilinje',
    srv_bikini_brazil: 'Brasiliansk bikini',
    srv_underarms:     'Armhuler',
    srv_lash_classic:  'Klassiske extensions',
    srv_lash_volume:   'Volume extensions',
    srv_lash_2_3:      'Etter 2–3 uker',
    srv_lash_3_4:      'Etter 3–4 uker',
    srv_lash_4_5:      'Etter 4–5 uker',
    srv_lash_lamination: 'Vippe-laminering',
    opt_g_face:        'Hårfjerning — Ansikt',
    opt_g_legs:        'Hårfjerning — Bein',
    opt_g_arms:        'Hårfjerning — Armer',
    opt_g_bikini:      'Hårfjerning — Bikini',
    opt_g_underarms:   'Hårfjerning — Armhuler',
    opt_g_lash_new:    'Vipper — Extensions',
    opt_g_lash_refill: 'Vipper — Påfyll',
    opt_g_lash_lam:    'Vipper — Laminering',
    book_btn:          'Bestill',
    products_label:    'Produkter',
    products_title:    'Profesjonell pleie hjemme',
    products_sub:      'Nøye utvalgte produkter som forlenger effekten av behandlingen. Hele utvalget — kommer snart.',
    products_tag:      'Kommer snart',
    prod1_title:       'Vippepleie',
    prod1_desc:        'Børster, rensemidler og serumer for å pleie vippe-extensions.',
    prod2_title:       'Etter hårfjerning',
    prod2_desc:        'Fuktighetsgivende oljer og kremer for sensitiv hud etter behandling.',
    prod3_title:       'Ansiktspleie',
    prod3_desc:        'Profesjonelle kremer, serumer og masker til daglig pleie.',
    products_cta_text: 'Interessert i et bestemt produkt? Skriv til meg — jeg gir råd og forteller hva som er på lager.',
    products_cta_btn:  'Kontakt om produkter',
    about_label:       'Om meg',
    about_title:       'Hei, kjære ✨',
    about_p1:          'Hvis du er her, betyr det at du tar deg tid til deg selv og din skjønnhet. Så glad for at du stakk innom. Jeg er Akvilė — en profesjonell skjønnhetsspesialist som jobber med sukkerhårfjerning for hele kroppen (den eneste i byen), voksing, vippe-extensions og laminering.',
    about_p2:          'Målet mitt er ikke bare et vakkert resultat, men også at du skal føle deg trygg på deg selv. Hver behandling og hvert produkt i studioet mitt er nøye utvalgt for å gi synlige resultater og en god opplevelse. Du er virkelig i gode hender.',
    about_li1:         '10 års erfaring siden 2016',
    about_li2:         'Den eneste sukkerhårfjerningen i byen',
    about_li3:         'Nøye utvalgte produkter',
    about_li4:         'Personlig oppmerksomhet til hver kunde',
    about_cta:         'Bestill et besøk',
    whyus_label:       'Hvorfor oss',
    whyus_title:       'Ditt valg er riktig',
    whyus_sub:         'Akva Studio — kvalitet, profesjonalisme og din skjønnhet i våre hender.',
    why1_t:            'Profesjonalisme',
    why1_d:            'Vi lærer og forbedrer oss konstant. Kun sertifiserte teknikere.',
    why2_t:            'Kvalitet',
    why2_d:            'Vi bruker kun prøvde, premium kvalitetsmaterialer.',
    why3_t:            'Komfort',
    why3_d:            'Varmt, koselig miljø. Føl deg hjemme.',
    why4_t:            'Unikhet',
    why4_d:            'Den eneste sukkerpasta hårfjerningen i din by.',
    portfolio_label:   'Våre arbeider',
    portfolio_title:   'Resultater taler for seg selv',
    portfolio_sub:     'Ekte arbeid. Ekte resultater. Ekte kunder.',
    reviews_label:     'Anmeldelser',
    reviews_title:     'Hva kundene sier',
    rev1_text:         'Veldig profesjonelt studio! Vippe-extensions varte 4 uker. Vil definitivt komme tilbake.',
    rev1_name:         'Laura K.',
    rev1_sub:          'Vippe-extensions',
    rev2_text:         'Sukkerpasta hårfjerning — for første gang i livet gjorde det ikke så vondt. Anbefaler til alle!',
    rev2_name:         'Monika P.',
    rev2_sub:          'Hårfjerning',
    rev3_text:         'Akvilė er veldig grundig og hyggelig. Studioet er koselig. Jeg kommer tilbake hver måned.',
    rev3_name:         'Gintarė S.',
    rev3_sub:          'Fast kunde',
    rev4_text:         'Beste vippe-laminering jeg har fått! Akvilė er så nøyaktig og rolig. Anbefaler på det sterkeste.',
    rev4_name:         'Janne H.',
    rev4_sub:          'Vippe-laminering',
    rev5_text:         'Sukkerhårfjerning var mye mindre vondt enn voks. Huden føltes glatt og rolig etterpå. Kommer tilbake!',
    rev5_name:         'Marie L.',
    rev5_sub:          'Sukkerhårfjerning',
    rev6_text:         'Vippene mine ser så naturlige og fyldige ut. Studioet er koselig og Akvilė er en ekte profesjonell.',
    rev6_name:         'Anita B.',
    rev6_sub:          'Vippe-extensions',
    booking_label:     'Bestilling',
    booking_title:     'Bestill ditt besøk',
    book_f1:           'Sanntids bestilling',
    book_f2:           'Automatisk bekreftelse på e-post',
    book_f3:           'Enkel avbestilling eller ombooking',
    booking_fallback:  'Kan ikke bestille? Send oss e-post',
    booking_open_full: 'Åpne bestilling i nytt vindu',
    portfolio_cap_1:   'Før · Etter',
    portfolio_cap_2:   'Bryn · Vipper',
    portfolio_cap_3:   'Volum-vipper',
    portfolio_cap_4:   'Klassiske vipper',
    portfolio_cap_5:   'Hårfjerning · Før · Etter',
    portfolio_cap_video: 'Behandling i øyeblikket',
    form_name:         'Navn',
    form_phone:        'Telefonnummer',
    form_service:      'Tjeneste',
    form_service_def:  'Velg en tjeneste',
    form_msg:          'Preferanser (valgfritt)',
    form_submit:       'Send forespørsel',
    form_note:         'Vi kontakter deg innen 24 timer · akvastudio75@gmail.com',
    form_success:      '✓ Takk! Din forespørsel er mottatt. Vi kontakter deg innen 24 timer.',
    footer_about:      'Profesjonelt skjønnhetsstudio. Vipper, laminering, hårfjerning.',
    footer_nav_t:      'Navigasjon',
    footer_contact_t:  'Kontakt',
    footer_legal_t:    'Juridisk',
    footer_legal_priv: 'Personvernerklæring',
    footer_legal_cookies: 'Cookie-erklæring',
    footer_legal_terms: 'Brukervilkår',
    footer_legal_rules: 'Bruksregler',
    footer_impressum_label: 'Ansvarlig person:',
    footer_impressum_person: '[ANSVARLIG PERSON]',
    footer_impressum_phone: '[TELEFON]',
    footer_copy:       '© 2025 Akva Studio. Alle rettigheter reservert.',

    // ── LEGAL · Personvernerklæring ──
    legal_priv_meta_title: 'Personvernerklæring — Akva Studio',
    legal_priv_eyebrow: 'Personvernerklæring',
    legal_priv_title:   'Personvernerklæring',
    legal_priv_updated: 'Sist oppdatert: [DATO]',
    legal_priv_h_intro: '1. Innledning',
    legal_priv_p_intro: 'Denne personvernerklæringen beskriver hvordan [SELSKAPSNAVN] (heretter — «Akva Studio», «vi») samler inn, bruker og oppbevarer dine personopplysninger når du bruker vårt nettsted [DOMAIN], bestiller behandlinger eller kjøper produkter. Vi respekterer ditt personvern og overholder personvernforordningen (GDPR) og norsk personopplysningslov.',
    legal_priv_h_controller: '2. Behandlingsansvarlig',
    legal_priv_p_controller: 'Behandlingsansvarlig: [SELSKAPSNAVN] · Adresse: [ADRESSE] · Org.nr.: [ORGNR] · E-post: akvastudio75@gmail.com · Telefon: [TELEFON] · Ansvarlig person: [ANSVARLIG PERSON]',
    legal_priv_h_data:  '3. Hvilke data vi samler inn',
    legal_priv_p_data_intro: 'Vi samler kun inn opplysninger som er nødvendige for å levere tjenestene:',
    legal_priv_li_data_1: 'Kontaktopplysninger — navn, telefon, e-post (i bestillingsskjemaet).',
    legal_priv_li_data_2: 'Bestillingsdata — valgt tjeneste, dato, tid, ønsker (via Setmore).',
    legal_priv_li_data_3: 'Kjøpsdata — ordreinformasjon, leveringsadresse, betalingsdetaljer (behandles av betalingsleverandør; vi lagrer ikke kortdata).',
    legal_priv_li_data_4: 'Tekniske data — IP-adresse, nettlesertype, cookies (se Cookie-erklæring).',
    legal_priv_link_cookies: 'Cookie-erklæring',
    legal_priv_h_purpose: '4. Formål og rettslig grunnlag',
    legal_priv_li_purpose_1: 'Tjenesteleveranse og bestillinger — oppfyllelse av avtale (GDPR art. 6(1)(b)).',
    legal_priv_li_purpose_2: 'Kommunikasjon ved henvendelser — berettiget interesse i å besvare spørsmål (GDPR art. 6(1)(f)).',
    legal_priv_li_purpose_3: 'Regnskap og rettslige forpliktelser — rettslig forpliktelse (GDPR art. 6(1)(c)).',
    legal_priv_li_purpose_4: 'Drift og sikkerhet av nettsted — berettiget interesse (GDPR art. 6(1)(f)).',
    legal_priv_h_share: '5. Hvem vi deler data med',
    legal_priv_p_share_intro: 'Dataene dine kan overføres til følgende databehandlere:',
    legal_priv_li_share_1: 'Setmore — bestillingssystem (Setmore Inc., USA).',
    legal_priv_li_share_2: 'Formspree — behandling av kontaktskjema (Formspree Inc., USA).',
    legal_priv_li_share_3: 'Vercel — hosting av nettsted (Vercel Inc., USA).',
    legal_priv_li_share_4: 'Sanity — produktkatalog CMS (Sanity.io AS, Norge).',
    legal_priv_li_share_5: 'Google — Google Fonts-tjeneste.',
    legal_priv_p_share_outro: 'Data kan overføres utenfor EU/EØS. I slike tilfeller sikrer vi tilstrekkelige tiltak (Standard Contractual Clauses).',
    legal_priv_h_retention: '6. Lagringstid',
    legal_priv_li_retention_1: 'Bestillingsdata — 3 år fra siste besøk.',
    legal_priv_li_retention_2: 'Kjøpsdata — 10 år (krav i bokføringsloven).',
    legal_priv_li_retention_3: 'Kontakthenvendelser — 1 år fra siste korrespondanse.',
    legal_priv_li_retention_4: 'Tekniske logger — opptil 90 dager.',
    legal_priv_h_rights: '7. Dine rettigheter',
    legal_priv_p_rights_intro: 'Etter GDPR har du rett til å:',
    legal_priv_li_rights_1: 'Få innsyn i og kopi av dataene dine.',
    legal_priv_li_rights_2: 'Kreve retting av uriktige opplysninger.',
    legal_priv_li_rights_3: 'Kreve sletting («retten til å bli glemt»).',
    legal_priv_li_rights_4: 'Begrense behandlingen.',
    legal_priv_li_rights_5: 'Dataportabilitet.',
    legal_priv_li_rights_6: 'Protestere mot behandling basert på berettiget interesse.',
    legal_priv_li_rights_7: 'Klage til tilsynsmyndigheten (i Norge — Datatilsynet; i Litauen — Statens datatilsynsinspektorat).',
    legal_priv_p_rights_contact: 'For å utøve disse rettighetene, kontakt oss på akvastudio75@gmail.com. Vi svarer innen 30 kalenderdager.',
    legal_priv_h_security: '8. Datasikkerhet',
    legal_priv_p_security: 'Vi anvender tekniske og organisatoriske tiltak for å sikre konfidensialitet og integritet: HTTPS-kryptering, tilgangskontroll, regelmessige sikkerhetskopier. Likevel kan ingen overføring over internett være 100% sikker — bruk ansvarlig.',
    legal_priv_h_changes: '9. Endringer',
    legal_priv_p_changes: 'Vi kan oppdatere denne erklæringen. Vi varsler vesentlige endringer på nettstedet eller via e-post. Nyeste versjon finnes alltid på denne siden.',
    legal_priv_h_contact: '10. Kontakt',
    legal_priv_p_contact: 'Personvern-spørsmål: akvastudio75@gmail.com',

    // ── LEGAL · Cookie-erklæring ──
    legal_cook_meta_title: 'Cookie-erklæring — Akva Studio',
    legal_cook_eyebrow: 'Cookie-erklæring',
    legal_cook_title:   'Cookie-erklæring',
    legal_cook_updated: 'Sist oppdatert: [DATO]',
    legal_cook_h_what:  '1. Hva er cookies',
    legal_cook_p_what:  'Cookies er små tekstfiler som nettleseren din lagrer på enheten når du besøker et nettsted. De hjelper nettstedet å huske dine valg (f.eks. språk), sikre funksjonalitet og forbedre brukeropplevelsen.',
    legal_cook_h_use:   '2. Hvordan vi bruker cookies',
    legal_cook_p_use:   'Akva Studio-nettstedet bruker et minimum av cookies og lokal lagring (localStorage), nødvendig kun for drift. Vi bruker ikke cookies for reklame eller tredjepartsanalyse.',
    legal_cook_h_types: '3. Cookie-typer',
    legal_cook_h_essential: '3.1. Nødvendige (essential)',
    legal_cook_p_essential: 'Disse cookies/nøklene er nødvendige for at nettstedet skal fungere og krever ikke samtykke:',
    legal_cook_th_name: 'Navn',
    legal_cook_th_purpose: 'Formål',
    legal_cook_th_duration: 'Varighet',
    legal_cook_td_lang: 'Lagrer brukerens valgte språk (LT/EN/NO) i localStorage.',
    legal_cook_td_cart: 'Innhold i handlekurv (localStorage). Lagres kun i din nettleser.',
    legal_cook_td_persistent: 'Til sletting',
    legal_cook_h_third: '3.2. Tredjepartstjenester',
    legal_cook_p_third: 'Når du besøker områder fra disse tjenestene, kan ekstra cookies bli brukt etter deres retningslinjer:',
    legal_cook_li_third_1: 'Setmore — bestillingsside.',
    legal_cook_li_third_2: 'Google Fonts — lasting av skrifttyper.',
    legal_cook_li_third_3: 'Vercel — hosting. Kan bruke tekniske cookies for sikkerhet.',
    legal_cook_h_manage: '4. Hvordan håndtere cookies',
    legal_cook_p_manage_intro: 'Du kan slette eller blokkere cookies i nettleserinnstillingene. Merk — enkelte funksjoner (f.eks. språkvalg, handlekurv) kan slutte å fungere.',
    legal_cook_li_manage_1: 'Chrome',
    legal_cook_li_manage_2: 'Firefox',
    legal_cook_li_manage_3: 'Safari',
    legal_cook_li_manage_4: 'Edge',
    legal_cook_h_changes: '5. Endringer',
    legal_cook_p_changes: 'Cookie-listen kan endres. Nyeste versjon finnes alltid på denne siden.',
    legal_cook_h_contact: '6. Kontakt',
    legal_cook_p_contact: 'Spørsmål om cookies: akvastudio75@gmail.com. For mer om databehandling, se Personvernerklæring.',
    legal_cook_link_priv: 'Personvernerklæring',

    // ── LEGAL · Brukervilkår ──
    legal_terms_meta_title: 'Brukervilkår — Akva Studio',
    legal_terms_eyebrow: 'Brukervilkår',
    legal_terms_title:   'Brukervilkår og kjøpsbetingelser',
    legal_terms_updated: 'Sist oppdatert: [DATO]',
    legal_terms_h_general: '1. Generelt',
    legal_terms_p_general: 'Disse brukervilkårene («Vilkårene») regulerer forholdet mellom [SELSKAPSNAVN] («Akva Studio») og besøkende / kunde på [DOMAIN]. Ved å bruke nettstedet, bestille behandlinger eller kjøpe produkter aksepterer du disse Vilkårene.',
    legal_terms_h_seller: '2. Selger',
    legal_terms_p_seller: '[SELSKAPSNAVN] · Adresse: [ADRESSE] · Org.nr.: [ORGNR] · MVA-nr.: [MVA-NR] · E-post: akvastudio75@gmail.com · Telefon: [TELEFON]',
    legal_terms_h_services: '3. Bestilling av behandlinger',
    legal_terms_li_serv_1: 'Behandlinger kan bestilles via Setmore-plattformen eller kontaktskjemaet.',
    legal_terms_li_serv_2: 'Etter bestilling mottar du bekreftelse på e-post.',
    legal_terms_li_serv_3: 'Priser og varighet er oppgitt på nettstedet. Endelig pris bekreftes av spesialisten ved oppmøte.',
    legal_terms_li_serv_4: 'Ansvar for oppgitte data (navn, telefon, e-post) ligger hos kunden.',
    legal_terms_h_cancel: '4. Avbestilling og ombooking',
    legal_terms_li_cancel_1: 'Avbestilling eller flytting kan skje senest 24 timer før — uten gebyr.',
    legal_terms_li_cancel_2: 'Mer enn 15 min. forsinkelse kan føre til forkortet eller avlyst behandling.',
    legal_terms_li_cancel_3: 'Ved gjentatte uteblivelser uten varsel forbeholder Akva Studio seg retten til å nekte service.',
    legal_terms_h_payment: '5. Betaling',
    legal_terms_li_pay_1: 'Behandlinger betales på stedet med kontanter eller kort.',
    legal_terms_li_pay_2: 'Produktbestillinger betales online via sikker betalingsleverandør. Akva Studio lagrer ikke kortdata.',
    legal_terms_li_pay_3: 'Alle priser inkluderer MVA (der det er aktuelt).',
    legal_terms_h_delivery: '6. Levering av produkter',
    legal_terms_li_del_1: 'Leveringstider og priser oppgis ved bestilling.',
    legal_terms_li_del_2: 'Ordrer behandles innen 1–3 virkedager.',
    legal_terms_li_del_3: 'Henting på stedet er gratis (etter avtale).',
    legal_terms_h_returns: '7. Retur og bytte',
    legal_terms_p_returns_intro: 'Etter litauisk / norsk forbrukerlov:',
    legal_terms_li_ret_1: 'Du kan returnere et uønsket produkt innen 14 dager etter mottak, hvis ubrukt og i original emballasje.',
    legal_terms_li_ret_2: 'Hygieneprodukter (kosmetikk med brutt forsegling, åpnede pakker) — ikke returnerbare ved lov.',
    legal_terms_li_ret_3: 'Defekte varer byttes gratis. Kontakt oss innen 14 dager etter at feilen oppdages.',
    legal_terms_li_ret_4: 'Returfrakt dekkes av kunden, med mindre varen er defekt.',
    legal_terms_p_returns_outro: 'Kontakt: akvastudio75@gmail.com',
    legal_terms_h_responsibility: '8. Ansvar',
    legal_terms_li_resp_1: 'Kunden må informere spesialisten om allergier, kontraindikasjoner og helsetilstander før behandling.',
    legal_terms_li_resp_2: 'Akva Studio er ikke ansvarlig for reaksjoner som skyldes ikke opplyst informasjon.',
    legal_terms_li_resp_3: 'Innholdet på nettstedet leveres «som det er»; vi tilstreber nøyaktighet, men garanterer ikke uavbrutt drift.',
    legal_terms_h_ip: '9. Immaterielle rettigheter',
    legal_terms_p_ip: 'Alt innhold (tekst, bilder, video, logo, design) tilhører Akva Studio eller dets lisensgivere. Kopiering, distribusjon eller kommersiell bruk uten skriftlig tillatelse er forbudt.',
    legal_terms_h_law: '10. Gjeldende rett og tvister',
    legal_terms_p_law: 'Disse Vilkårene reguleres av [LANDETS] rett. Tvister løses gjennom forhandlinger, ellers ved kompetent domstol etter selgerens registrerte sted. Forbrukere kan også bruke EUs nettbaserte tvisteløsningsplattform.',
    legal_terms_h_changes: '11. Endring av vilkår',
    legal_terms_p_changes: 'Akva Studio kan endre disse Vilkårene. Versjonen som gjaldt ved bestilling / booking er bindende.',
    legal_terms_h_contact: '12. Kontakt',
    legal_terms_p_contact: 'Spørsmål om vilkårene: akvastudio75@gmail.com. Se også Personvernerklæring og Cookie-erklæring.',
    legal_terms_link_priv: 'Personvernerklæring',
    legal_terms_link_cookies: 'Cookie-erklæring',

    // ── LEGAL · Bruksregler ──
    legal_rules_meta_title: 'Bruksregler — Akva Studio',
    legal_rules_eyebrow: 'Bruksregler',
    legal_rules_title:   'Bruksregler',
    legal_rules_updated: 'Sist oppdatert: [DATO]',
    legal_rules_h_scope: '1. Virkeområde',
    legal_rules_p_scope: 'Disse reglene regulerer bruken av Akva Studios nettsted [DOMAIN]. Ved å bruke nettstedet samtykker du til å følge dem. Hvis du ikke samtykker — vennligst ikke bruk nettstedet.',
    legal_rules_p_scope_note: 'Reglene utfyller våre Brukervilkår og kjøpsbetingelser, Personvernerklæring og Cookie-erklæring.',
    legal_rules_link_terms: 'Brukervilkår og kjøpsbetingelser',
    legal_rules_link_priv: 'Personvernerklæring',
    legal_rules_link_cookies: 'Cookie-erklæring',
    legal_rules_h_access: '2. Tilgang til nettstedet',
    legal_rules_li_access_1: 'Nettstedet er tilgjengelig 24/7, men midlertidige driftsforstyrrelser kan oppstå pga. vedlikehold eller eksterne forhold.',
    legal_rules_li_access_2: 'Akva Studio garanterer ikke uavbrutt, feilfri drift.',
    legal_rules_li_access_3: 'Vi forbeholder oss retten til når som helst å endre, suspendere eller avslutte nettstedet uten forvarsel.',
    legal_rules_h_user: '3. Brukerens plikter',
    legal_rules_p_user_intro: 'Ved å bruke nettstedet forplikter du deg til å:',
    legal_rules_li_user_1: 'Oppgi nøyaktig og sannferdig informasjon (ved bestilling eller kjøp).',
    legal_rules_li_user_2: 'Bruke nettstedet kun til lovlige formål.',
    legal_rules_li_user_3: 'Ikke skade eller forstyrre nettstedets drift.',
    legal_rules_li_user_4: 'Respektere andre brukeres og Akva Studios rettigheter.',
    legal_rules_li_user_5: 'Beskytte påloggingsdata (hvis aktuelt) og ikke dele dem med tredjeparter.',
    legal_rules_h_prohibited: '4. Forbudt aktivitet',
    legal_rules_p_prohibited_intro: 'Ved bruk av nettstedet kan du ikke:',
    legal_rules_li_prohibited_1: 'Forsøke å hacke, skanne eller på annen måte bryte nettstedets sikkerhet.',
    legal_rules_li_prohibited_2: 'Bruke automatiserte verktøy (bots, scrapers, crawlers) uten skriftlig samtykke.',
    legal_rules_li_prohibited_3: 'Laste opp eller sende virus, skadelig kode eller annet skadelig innhold.',
    legal_rules_li_prohibited_4: 'Oppgi falsk informasjon eller utgi deg for å være en annen person.',
    legal_rules_li_prohibited_5: 'Samle inn data fra andre brukere uten deres samtykke.',
    legal_rules_li_prohibited_6: 'Bruke nettstedet til reklame, spam eller kommersielle formål uten tillatelse.',
    legal_rules_li_prohibited_7: 'Kopiere, endre eller distribuere innholdet uten skriftlig samtykke.',
    legal_rules_li_prohibited_8: 'Omgå eller forsøke å omgå tekniske beskyttelsestiltak.',
    legal_rules_h_content: '5. Brukergenerert innhold',
    legal_rules_p_content: 'Hvis du sender inn anmeldelser, kommentarer eller annet innhold på nettstedet, gir du Akva Studio en ikke-eksklusiv, varig rett til å bruke, redigere og publisere det til markedsføringsformål. Du er ansvarlig for nøyaktigheten og lovligheten av det innsendte innholdet.',
    legal_rules_p_content_remove: 'Akva Studio forbeholder seg retten til uten varsel å fjerne innhold som bryter disse reglene, lovverket eller tredjeparts rettigheter.',
    legal_rules_h_ip: '6. Immaterielle rettigheter',
    legal_rules_p_ip: 'Alt innhold på nettstedet (tekst, bilder, video, logo, grafikk, design, kode) tilhører Akva Studio eller dets lisensgivere og er beskyttet av opphavsrett og andre lover om immaterielle rettigheter. Du kan vise innhold til personlig, ikke-kommersiell bruk.',
    legal_rules_p_ip_brand: 'Navnet «Akva Studio», logoen og den visuelle identiteten er beskyttede varemerker. Bruk uten skriftlig samtykke er forbudt.',
    legal_rules_h_links: '7. Lenker til tredjeparts nettsteder',
    legal_rules_p_links: 'Nettstedet kan inneholde lenker til tredjeparts nettsteder (f.eks. Setmore, Sanity, sosiale medier). Akva Studio er ikke ansvarlig for innholdet, personvernpraksisen eller driften av disse nettstedene. Ved besøk gjør deg kjent med deres regler.',
    legal_rules_h_liability: '8. Ansvarsbegrensning',
    legal_rules_li_liability_1: 'Innholdet leveres «som det er» uten noen garantier.',
    legal_rules_li_liability_2: 'Akva Studio er ikke ansvarlig for indirekte, tilfeldige eller følgeskader som oppstår ved bruk av nettstedet.',
    legal_rules_li_liability_3: 'Vi er ikke ansvarlige for tap av data, enhetsfeil eller andre problemer som følge av nettstedsbruk.',
    legal_rules_li_liability_4: 'Disse begrensningene gjelder ikke der loven ikke tillater dem.',
    legal_rules_h_consequences: '9. Konsekvenser av brudd',
    legal_rules_p_consequences: 'Ved brudd på disse reglene forbeholder Akva Studio seg retten til å:',
    legal_rules_li_consequences_1: 'Begrense eller avslutte tilgang til nettstedet.',
    legal_rules_li_consequences_2: 'Fjerne innhold knyttet til bruddet.',
    legal_rules_li_consequences_3: 'Kreve erstatning i henhold til loven.',
    legal_rules_li_consequences_4: 'Henvende seg til politiet hvis bruddet utgjør lovbrudd.',
    legal_rules_h_law: '10. Gjeldende rett',
    legal_rules_p_law: 'Disse reglene reguleres av [LANDETS] rett. Tvister løses gjennom forhandlinger, ellers ved kompetent domstol etter selgerens registrerte sted.',
    legal_rules_h_changes: '11. Endringer',
    legal_rules_p_changes: 'Akva Studio kan endre disse reglene. Nyeste versjon publiseres alltid på denne siden. Fortsatt bruk av nettstedet etter endringer betyr at du aksepterer den oppdaterte versjonen.',
    legal_rules_h_contact: '12. Kontakt',
    legal_rules_p_contact: 'Spørsmål om bruksreglene: akvastudio75@gmail.com',
  }
};

// ── STATE ──────────────────────────────────
let currentLang = localStorage.getItem('akva_lang') || 'lt';

// ── APPLY LANGUAGE ─────────────────────────
function applyLang(lang) {
  currentLang = lang;
  localStorage.setItem('akva_lang', lang);

  const t = translations[lang];
  if (!t) return;

  // Update all [data-i18n] elements
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) el.textContent = t[key];
  });

  // Update all [data-i18n-placeholder] elements
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (t[key] !== undefined) el.placeholder = t[key];
  });

  // Update all [data-i18n-label] elements (e.g. <optgroup label="">)
  document.querySelectorAll('[data-i18n-label]').forEach(el => {
    const key = el.getAttribute('data-i18n-label');
    if (t[key] !== undefined) el.label = t[key];
  });

  // Update lang buttons
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });

  // Update html lang attr
  document.documentElement.lang = lang;
}

// ── HEADER SCROLL ──────────────────────────
function initScrollHeader() {
  const header = document.querySelector('.header');
  if (!header) return;

  window.addEventListener('scroll', () => {
    header.classList.toggle('scrolled', window.scrollY > 20);
  }, { passive: true });
}

// ── MOBILE NAV ─────────────────────────────
function initMobileNav() {
  const burger = document.querySelector('.nav-burger');
  const mobileNav = document.querySelector('.mobile-nav');
  const closeBtn = document.querySelector('.mobile-nav-close');

  if (!burger || !mobileNav) return;

  burger.addEventListener('click', () => {
    mobileNav.classList.add('open');
    document.body.style.overflow = 'hidden';
  });

  const closeMobileNav = () => {
    mobileNav.classList.remove('open');
    document.body.style.overflow = '';
  };

  if (closeBtn) closeBtn.addEventListener('click', closeMobileNav);

  mobileNav.querySelectorAll('a').forEach(link => {
    link.addEventListener('click', closeMobileNav);
  });
}

// ── LANG SWITCHER ──────────────────────────
function initLangSwitcher() {
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      const lang = btn.dataset.lang;
      if (lang && translations[lang]) applyLang(lang);
    });
  });
}

// ── CONTACT FORM ───────────────────────────
function initForm() {
  const form = document.querySelector('#booking-form');
  if (!form) return;

  form.addEventListener('submit', async (e) => {
    e.preventDefault();

    const submitBtn = form.querySelector('.form-submit');
    const successMsg = form.querySelector('.form-success');

    submitBtn.disabled = true;
    submitBtn.textContent = '...';

    const data = {
      name:    form.querySelector('[name="name"]').value.trim(),
      phone:   form.querySelector('[name="phone"]').value.trim(),
      service: form.querySelector('[name="service"]').value,
      message: form.querySelector('[name="message"]').value.trim(),
    };

    try {
      // Formspree endpoint — replace ACTION_URL with real Formspree URL
      const res = await fetch(form.action, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Accept': 'application/json' },
        body: JSON.stringify(data),
      });

      if (res.ok) {
        form.reset();
        if (successMsg) {
          successMsg.textContent = translations[currentLang].form_success;
          successMsg.classList.add('visible');
        }
      } else {
        throw new Error('Form error');
      }
    } catch {
      submitBtn.disabled = false;
      submitBtn.setAttribute('data-i18n', 'form_submit');
      submitBtn.textContent = translations[currentLang].form_submit;
      alert('Klaida. Bandykite vėliau arba rašykite: akvastudio75@gmail.com');
    }
  });
}

// ── SMOOTH SCROLL ──────────────────────────
function initSmoothScroll() {
  document.querySelectorAll('a[href^="#"]').forEach(link => {
    link.addEventListener('click', (e) => {
      const target = document.querySelector(link.getAttribute('href'));
      if (!target) return;
      e.preventDefault();
      const top = target.getBoundingClientRect().top + window.scrollY - 80;
      window.scrollTo({ top, behavior: 'smooth' });
    });
  });
}

// ── CART ICON COUNTER (homepage'ui — be ES module dependencies) ──
function initCartIcon() {
  const icons = document.querySelectorAll('[data-cart-icon]');
  if (icons.length === 0) return;
  const update = () => {
    let count = 0;
    try {
      const raw = localStorage.getItem('akva_cart_v1');
      if (raw) {
        const cart = JSON.parse(raw);
        count = (cart.items || []).reduce((sum, i) => sum + (i.quantity || 0), 0);
      }
    } catch { /* ignore */ }
    icons.forEach(icon => {
      const counter = icon.querySelector('[data-cart-count]');
      if (counter) {
        counter.textContent = count;
        counter.classList.toggle('is-empty', count === 0);
      }
    });
  };
  update();
  window.addEventListener('storage', (e) => {
    if (e.key === 'akva_cart_v1') update();
  });
}

// ── INIT ───────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  initScrollHeader();
  initMobileNav();
  initLangSwitcher();
  initSmoothScroll();
  initForm();
  initCartIcon();
  applyLang(currentLang);
});
